### ISSUE TITLE
Does only work with Linux Containers

### ISSUE THREAD

**Issue by mwawrusch** [jacobtomlinson/go-container-action#2]
Unfortunately, this version only works with Linux containers (Container action is only supported on Linux from GitHub actions). Is there any way to make this work on other container types? I would need it to change some content pre-building android and ios apps.

Thanks

**Comment by jacobtomlinson** [comment]
I'm afraid GitHub only supports Linux with container actions.

This repo is a template repo for container actions written in go and therefore we can only support Linux.
